version: '3.8'
services:
  web:
    build:
      context: ./frontend
#      dockerfile: DockerfileDev
      dockerfile: DockerfileProd
    ports:
#      - '8081:3000'
      - '8081:80'
  api:
    build:
      context: ./CustomerApp
    ports:
      - '8080:8080'
