export const states=[
      "CA",
      "TX",
      "PA",
      "NY",
      "FL",
      "IL"
    ].sort();
export const city =[
      "Glen Rock",
      "Kilgore",
      "Margaretville",
      "Blooming Grove",
      "Orangeburg",
      "Clune",
      "Carlotta",
      "Loami",
      "New York City",
      "Irvine",
      "Dallas",
      "Altair",
      "Logan",
      "Port Gibson",
      "Farmington",
      "Armagh",
      "Atglen",
      "Huntington Beach",
      "Helm",
      "Nicholson",
      "Rock Tavern",
      "Napa",
      "Oakford",
      "Big Indian",
      "Clearwater",
      "Beacon",
      "Emporium",
      "Karns City",
      "Keller",
      "Glendale",
      "Notrees",
      "Oaks",
      "Hawthorne",
      "Cottekill",
      "Rossville",
      "Corona",
      "San Angelo",
      "Armonk",
      "Desdemona",
      "Fields Landing",
      "Keisterville",
      "Saint Bonaventure",
      "Hampton",
      "Saint Petersburg",
      "Downey",
      "Oakdale",
      "Clarks Mills",
      "Falls City",
      "Montrose",
      "Melville",
      "Greenport",
      "Greenview",
      "Coleman",
      "Philadelphia",
      "Key West",
      "Olmsted",
      "Murrayville",
      "Aledo",
      "San Antonio",
      "Brownville",
      "Fenelton",
      "Moriches",
      "Payson",
      "Oakland",
      "Corsica",
      "Granbury",
      "Lockhart",
      "Cochranton",
      "Meridian",
      "Norwalk",
      "El Paso",
      "Lubbock",
      "Barneveld",
      "Falconer",
      "Northport",
      "Karnack",
      "Morrisdale",
      "Mount Morris",
      "Nanuet",
      "Daly City",
      "Allentown",
      "Jay",
      "Grandview",
      "Pomona",
      "Galatia",
      "Chester Heights",
      "Loxahatchee",
      "Mc Veytown",
      "Bronx",
      "Hudson",
      "Naples",
      "Port Richey",
      "New Waverly",
      "Leetsdale",
      "Harper",
      "Sacramento",
      "Phelps",
      "Knowlesville",
      "Parker Dam",
      "Fiddletown",
      "Holliday",
      "Azusa",
      "Breesport",
      "Mc Nabb",
      "June Lake",
      "Eureka",
      "Ringwood",
      "Lakeland",
      "Lorenzo",
      "Belfast",
      "Buellton",
      "San Diego",
      "Cokeburg",
      "New Memphis",
      "Gainesville",
      "Pittsburgh",
      "Bonita Springs",
      "Albany",
      "Manor",
      "Bolivar",
      "Marienville",
      "Joliet",
      "North Tonawanda",
      "Palmyra",
      "Port Ewen",
      "Cisco",
      "Lanark Village",
      "Beaver Falls",
      "Los Angeles",
      "Ratcliff",
      "Haines City",
      "Mc Clellandtown",
      "Port Saint Lucie",
      "Cape Coral",
      "Marathon",
      "Rockwood",
      "Jermyn",
      "Dieterich",
      "Grassflat",
      "O Brien",
      "Fort Myers",
      "Port Charlotte",
      "Cleveland",
      "Nokomis",
      "Pecos",
      "Clarion",
      "Blairsden-Graeagle",
      "Altona",
      "North Washington",
      "Lomax",
      "Palmdale",
      "New Boston",
      "Grand Ridge",
      "Irvington",
      "Rule",
      "Mulberry Grove",
      "Orient",
      "May",
      "Eagarville",
      "Howes Cave",
      "Dunlevy",
      "Harmony",
      "Lake Jackson",
      "Cressona",
      "Harborcreek",
      "Rock Glen",
      "East Rochester",
      "Melbourne",
      "Dongola",
      "Jordanville",
      "Bristol",
      "Port Costa",
      "Brooklyn",
      "Medford",
      "Nazareth",
      "Newhall",
      "Quanah",
      "Cowlesville",
      "Grenada",
      "Houston",
      "Deltona",
      "Claremont",
      "Laredo",
      "Humble",
      "Downsville",
      "Goreville",
      "Mount Vernon",
      "Purmela",
      "Newark Valley",
      "Bellmore",
      "Laguna Hills",
      "Chatham",
      "Lawn",
      "Bonfield",
      "Dublin",
      "Camden",
      "Jefferson",
      "De Lancey",
      "Bynum",
      "Garrattsville",
      "Putnam",
      "Hedley",
      "Cross Plains",
      "Angwin",
      "Beasley",
      "Leonard",
      "Mifflin",
      "Oriskany Falls",
      "Brandon",
      "Dell City",
      "Prairie Hill",
      "Roma",
      "Saint James City",
      "Hannawa Falls",
      "Lolita",
      "Orange Park",
      "Pembroke Township",
      "Moro",
      "North East",
      "Sachse",
      "Mill Creek",
      "Montandon",
      "Lowville",
      "Mountain Center",
      "Lakeport",
      "Oak Hill",
      "Indian Wells"
    ].sort();
export const merchants =[
      "Bahringer Group",
      "Stoltenberg-Beatty",
      "Koss and Sons",
      "Lehner, Reichert and Mills",
      "Mante, Luettgen and Hackett",
      "Ruecker Group",
      "Daugherty LLC",
      "Eichmann, Bogan and Rodriguez",
      "Haag-Blanda",
      "Pouros-Conroy",
      "Kuhic Inc",
      "Kilback and Sons",
      "Kunze, Larkin and Mayert",
      "Hermann-Gaylord",
      "Marks Inc",
      "Bruen-Yost",
      "Wuckert-Goldner",
      "Labadie LLC",
      "Roberts-Beahan",
      "Stracke-Lemke",
      "Corwin-Romaguera",
      "Medhurst, Labadie and Gottlieb",
      "Kozey-McDermott",
      "Herman Inc",
      "Nienow, Ankunding and Collier",
      "Homenick LLC",
      "Huel Ltd",
      "Waelchi Inc",
      "Block Group",
      "Torp-Lemke",
      "Koss, Hansen and Lueilwitz",
      "Sporer Inc",
      "Reichert, Shanahan and Hayes",
      "Carroll PLC",
      "Pacocha-Bauch",
      "Morissette, Weber and Wiegand",
      "Armstrong, Walter and Gottlieb",
      "Thiel-Thiel",
      "Bailey-Morar",
      "Mayert Group",
      "Brown-Greenholt",
      "Leannon-Nikolaus",
      "Rempel PLC",
      "Champlin-Casper",
      "Leffler-Goldner",
      "Welch, Rath and Koepp",
      "Terry-Huel",
      "Parisian, Schiller and Altenwerth",
      "Schamberger-O'Keefe",
      "Buckridge PLC",
      "Robel, Cummerata and Prosacco",
      "Lakin, Ferry and Beatty",
      "Turner, Ziemann and Lehner",
      "Schultz, Simonis and Little",
      "Schoen, Kuphal and Nitzsche",
      "Gottlieb Group",
      "Denesik and Sons",
      "Murray Ltd",
      "Wintheiser, Dietrich and Schimmel",
      "Reichel, Bradtke and Blanda",
      "Romaguera, Cruickshank and Greenholt",
      "Quitzon, Green and Bashirian",
      "Corwin-Gorczany",
      "Breitenberg-Hermiston",
      "Zieme, Bode and Dooley",
      "Olson, Becker and Koch",
      "Sporer-Keebler",
      "Gerhold LLC",
      "Weber, Thiel and Hammes",
      "Kutch-Ferry",
      "Little, Gutmann and Lynch",
      "Wilkinson LLC",
      "Crona and Sons",
      "Bartoletti-Wunsch",
      "Kuhic LLC",
      "Veum-Koelpin",
      "Willms, Kris and Bergnaum",
      "Parker, Nolan and Trantow",
      "Gottlieb, Considine and Schultz",
      "Kerluke Inc",
      "Hagenes, Kohler and Hoppe",
      "Pouros, Walker and Spencer",
      "Wiza LLC",
      "Beier and Sons",
      "Reynolds-Schinner",
      "Rohan, White and Aufderhar",
      "Ziemann-Waters",
      "Dooley Inc",
      "Ledner, Hartmann and Feest",
      "Cruickshank-Mills",
      "Bahringer-Larson",
      "Bradtke PLC",
      "Stark-Batz",
      "Little-Gleichner",
      "McCullough LLC",
      "Kozey-Boehm",
      "Marvin-Lind",
      "Hermiston, Pacocha and Smith",
      "Wolf Inc",
      "Kautzer and Sons",
      "Wuckert, Wintheiser and Friesen",
      "Wisozk and Sons",
      "Douglas, Schneider and Turner",
      "Monahan, Hermann and Johns",
      "Rodriguez Group",
      "Ruecker, Beer and Collier",
      "Medhurst Inc",
      "Cummerata-Hilpert",
      "Collier Inc",
      "Waelchi-Wolf",
      "Gottlieb-Hansen",
      "Roob, Conn and Tremblay",
      "Berge-Hills",
      "Rippin-VonRueden",
      "Hackett Group",
      "Beier LLC",
      "Hintz, Bauch and Smith",
      "Cassin-Harvey",
      "Schaefer, McGlynn and Bosco",
      "Tromp Group",
      "Pacocha-Weissnat",
      "Swaniawski, Bahringer and Ledner",
      "Howe Ltd",
      "Hackett-Lueilwitz",
      "Dach-Borer",
      "Kris-Kertzmann",
      "Pollich LLC",
      "Kilback, Nitzsche and Leffler",
      "Becker, Harris and Harvey",
      "Cole PLC",
      "Morar Inc",
      "Erdman-Schaden",
      "Turner, Ruecker and Parisian",
      "Johnson, Runolfsdottir and Mayer",
      "Schuppe-Schuppe",
      "Brown PLC",
      "O'Keefe-Wisoky",
      "Spencer PLC",
      "Schroeder, Hauck and Treutel",
      "Treutel-King",
      "Gleason and Sons",
      "Lubowitz, Terry and Stracke",
      "Kling-Grant",
      "Langworth LLC",
      "Skiles-Ankunding",
      "Okuneva, Schneider and Rau",
      "Kutch and Sons",
      "Brekke and Sons",
      "Connelly PLC",
      "O'Hara-Wilderman",
      "Nader-Heller",
      "Bins, Balistreri and Beatty",
      "Swaniawski, Lowe and Robel",
      "Schoen, Nienow and Bauch",
      "Huels-Hahn",
      "Gaylord-Powlowski",
      "Baumbach, Strosin and Nicolas",
      "Daugherty-Thompson",
      "Lemke and Sons",
      "Morissette LLC",
      "Streich, Dietrich and Barton",
      "Eichmann-Kilback",
      "Donnelly PLC",
      "Gutmann-Upton",
      "Kozey-Kuhlman",
      "Wiza, Schaden and Stark",
      "Adams, Kovacek and Kuhlman",
      "Schmeler, Bashirian and Price",
      "Lockman, West and Runte",
      "Runte-Mohr",
      "Reilly and Sons",
      "Durgan-Auer",
      "Predovic Inc",
      "Cartwright-Harris",
      "Conroy-Emard",
      "Spencer-Runolfsson",
      "Turcotte, McKenzie and Koss",
      "Kutch LLC",
      "McDermott-Weimann",
      "Larkin Ltd",
      "Kassulke Inc",
      "Corwin-Collins",
      "Boehm, Block and Jakubowski",
      "Crist, Jakubowski and Littel",
      "Fisher Inc",
      "Reichel LLC",
      "Kerluke, Kertzmann and Wiza",
      "Christiansen, Goyette and Schamberger",
      "Moore, Williamson and Emmerich",
      "Huel, Hammes and Witting",
      "Emard Inc",
      "Deckow-Dare",
      "Swift PLC",
      "Medhurst PLC",
      "Abbott-Steuber",
      "Bednar Inc",
      "Feil-Morar",
      "Cormier, Stracke and Thiel",
      "Champlin and Sons",
      "Langworth, Boehm and Gulgowski",
      "Douglas-White",
      "Waters-Cruickshank",
      "Kulas Group",
      "Jast and Sons",
      "Auer-Mosciski",
      "Connelly, Reichert and Fritsch",
      "Fadel-Hilpert",
      "Fadel, Mertz and Rippin",
      "Hills-Boyer",
      "Kub PLC",
      "Lockman Ltd",
      "Lang, Towne and Schuppe",
      "Kris-Padberg",
      "Harris Inc",
      "Schimmel-Olson",
      "Friesen-Stamm",
      "Herzog Ltd",
      "Bahringer-Streich",
      "Torp-Labadie",
      "Witting, Beer and Ernser",
      "Kilback LLC",
      "Moore, Dibbert and Koepp",
      "Hoppe, Harris and Bednar",
      "Heller-Langosh",
      "Wiegand-Lowe",
      "Schmitt Inc",
      "Abbott-Rogahn",
      "Bernhard Inc",
      "Botsford Ltd",
      "Parker-Kunde",
      "Towne, Greenholt and Koepp",
      "Zulauf LLC",
      "Mosciski Group",
      "Boyer-Haley",
      "Monahan, Bogisich and Ledner",
      "Erdman-Kertzmann",
      "Greenholt, Jacobi and Gleason",
      "Eichmann, Hayes and Treutel",
      "Effertz, Welch and Schowalter",
      "Bernier, Streich and Jewess",
      "Smitham-Boehm",
      "O'Keefe-Hudson",
      "Grimes LLC",
      "Howe PLC",
      "Hettinger, McCullough and Fay",
      "Kling Inc",
      "Pagac LLC",
      "Botsford PLC",
      "White and Sons",
      "Boehm, Predovic and Reinger",
      "Volkman-Predovic",
      "Baumbach, Hodkiewicz and Walsh",
      "Kihn, Brakus and Goyette",
      "Zboncak LLC",
      "VonRueden Group",
      "Runolfsdottir, Mueller and Hand",
      "Hermann and Sons",
      "Bednar PLC",
      "Block-Hauck",
      "Hills-Olson",
      "Flatley Group",
      "Fahey Inc",
      "Block-Parisian",
      "Jacobi Inc",
      "Stiedemann Inc",
      "Kassulke PLC",
      "Emmerich-Luettgen",
      "Friesen Ltd",
      "Volkman PLC",
      "Macejkovic-Lesch",
      "Spinka Inc",
      "Paucek-Wiza",
      "Luettgen PLC",
      "Hodkiewicz, Prohaska and Paucek",
      "Miller-Harris",
      "Friesen-Ortiz",
      "Ruecker-Mayert",
      "Funk Group",
      "Bins-Tillman",
      "Schaefer, Maggio and Daugherty",
      "Friesen Inc",
      "Lesch, D'Amore and Brown",
      "Gulgowski LLC",
      "Ritchie, Oberbrunner and Cremin",
      "Gislason Group",
      "Boyer PLC",
      "Metz, Russel and Metz",
      "Lind, Huel and McClure",
      "Swaniawski, Nitzsche and Welch",
      "Rolfson-Kunde",
      "Hagenes, Hermann and Stroman",
      "Stanton, Jakubowski and Baumbach",
      "Osinski, Ledner and Leuschke",
      "Heidenreich PLC",
      "Beer-Jast",
      "Kutch-Wilderman",
      "Zemlak, Tillman and Cremin",
      "Ferry, Reichel and DuBuque",
      "Parisian and Sons",
      "Eichmann-Russel",
      "Feil, Hilpert and Koss",
      "Prohaska-Murray",
      "Rempel Inc",
      "Padberg-Rogahn",
      "Fadel Inc",
      "Hirthe-Beier",
      "Renner Ltd",
      "Altenwerth-Kilback",
      "Effertz LLC",
      "O'Connell, Botsford and Hand",
      "Kemmer-Reinger",
      "Cartwright PLC",
      "Denesik, Powlowski and Pouros",
      "Reichert-Weissnat",
      "Kris-Weimann",
      "Abshire PLC",
      "Berge, Kautzer and Harris",
      "Nienow, Barrows and Romaguera",
      "Swift, Bradtke and Marquardt",
      "Graham, Hegmann and Hammes",
      "Kerluke-Abshire",
      "Durgan, Gislason and Spencer",
      "Windler LLC",
      "Kilback Group",
      "Morissette PLC",
      "Bechtelar-Rippin",
      "Miller-Hauck",
      "Streich, Rolfson and Wilderman",
      "Baumbach, Feeney and Morar",
      "Thompson-Gleason",
      "Dietrich-Fadel",
      "Johnston, Nikolaus and Maggio",
      "Romaguera and Sons",
      "Zemlak Group",
      "Ferry, Lynch and Kautzer",
      "Jaskolski-Vandervort",
      "McCullough Group",
      "Ebert-Daugherty",
      "Smitham-Schiller",
      "Nader-Maggio",
      "Wilkinson PLC",
      "Harris, Gusikowski and Heaney",
      "Runte, Green and Emard",
      "Kub-Heaney",
      "Little Ltd",
      "Hartmann, Rowe and Hermann",
      "Jacobi and Sons",
      "Vandervort-Funk",
      "Roberts, Daniel and Macejkovic",
      "Lowe, Dietrich and Erdman",
      "Bauch-Blanda",
      "Emmerich-Rau",
      "Heller PLC",
      "Raynor, Feest and Miller",
      "Williamson LLC",
      "Zboncak, Rowe and Murazik",
      "Hudson-Ratke",
      "Goyette-Herzog",
      "Auer LLC",
      "Pacocha-O'Reilly",
      "Halvorson Group",
      "Botsford and Sons",
      "Bernier and Sons",
      "Johns-Hoeger",
      "Boyer-Reichert",
      "Stokes, Christiansen and Sipes",
      "McKenzie-Huels",
      "Rau-Robel",
      "Ledner-Pfannerstill",
      "Nitzsche, Kessler and Wolff",
      "Bins-Howell",
      "Reilly, Heaney and Cole",
      "Prosacco LLC",
      "Barton Inc",
      "Rowe-Vandervort",
      "Jakubowski Inc",
      "Auer-West",
      "Langosh, Wintheiser and Hyatt",
      "Hauck, Dietrich and Funk",
      "Volkman Ltd",
      "Berge LLC",
      "Weber and Sons",
      "Bahringer, Osinski and Block",
      "Ankunding LLC",
      "Berge-Ullrich",
      "Friesen-D'Amore",
      "Kerluke, Considine and Macejkovic",
      "Heller-Abshire",
      "Kirlin and Sons",
      "Stamm-Rodriguez",
      "Lebsack and Sons",
      "Huels-Nolan",
      "Bogisich-Homenick",
      "Connelly-Carter",
      "Turner LLC",
      "Mohr-Bayer",
      "Crooks and Sons",
      "Mohr Inc",
      "Schoen-Quigley",
      "Schneider, Hayes and Nikolaus",
      "Ratke and Sons",
      "Cummings LLC",
      "Hickle Group",
      "Stark-Koss",
      "Gleason-Macejkovic",
      "Windler, Goodwin and Kovacek",
      "Dare, Fritsch and Zboncak",
      "Mraz-Herzog",
      "Yost-Rogahn",
      "Klocko LLC",
      "Flatley-Durgan",
      "Schiller, Blanda and Johnson",
      "Rau and Sons",
      "Turcotte, Batz and Buckridge",
      "Hintz-Bruen",
      "Price Inc",
      "Schmitt Ltd",
      "Dare-Gibson",
      "Romaguera, Wehner and Tromp",
      "Strosin-Cruickshank",
      "Cummerata-Jones",
      "Walter, Hettinger and Kessler",
      "Lind-Buckridge",
      "Reinger, Weissnat and Strosin",
      "Haley, Batz and Auer",
      "Kihn-Schuster",
      "Kuphal-Toy",
      "Jenkins, Hauck and Friesen",
      "Schoen Ltd",
      "McDermott-Rice",
      "Trantow PLC",
      "Rau-Grant",
      "Jast Ltd",
      "Bernhard, Grant and Langworth",
      "Kunde-Sanford",
      "Turner and Sons",
      "Tillman, Fritsch and Schmitt",
      "Hermiston, Russel and Price",
      "Streich Ltd",
      "Jerde-Hermann",
      "Dibbert and Sons",
      "Will Ltd",
      "Hoppe-Parisian",
      "Stehr, Jewess and Schimmel",
      "Altenwerth, Cartwright and Koss",
      "Tromp, Kerluke and Glover",
      "Mosciski, Ziemann and Farrell",
      "Goyette-Gerhold",
      "Goldner-Lemke",
      "Barton LLC",
      "Schumm, McLaughlin and Carter",
      "Streich, Hansen and Veum",
      "Raynor, Reinger and Hagenes",
      "Reichert, Huels and Hoppe",
      "Kessler Group",
      "Hyatt-Blick",
      "Murray-Smitham",
      "Hills, Hegmann and Schaefer",
      "Runolfsson and Sons",
      "Thiel Ltd",
      "Nicolas, Hills and McGlynn",
      "Hahn, Bahringer and McLaughlin",
      "Zboncak Ltd",
      "Monahan-Morar",
      "Doyle Ltd",
      "Pfeffer and Sons",
      "Hilpert-Conroy",
      "Wilkinson Ltd",
      "Kemmer-Buckridge",
      "Lynch-Mohr",
      "Kuphal-Bartoletti",
      "Haley Group",
      "Hammes-Beatty",
      "Rutherford-Mertz",
      "Simonis-Prohaska",
      "Kovacek Ltd",
      "Daugherty, Pouros and Beahan",
      "Sawayn PLC",
      "Deckow-O'Conner",
      "Heathcote, Yost and Kertzmann",
      "McLaughlin, Armstrong and Koepp",
      "Beier-Hyatt",
      "Adams-Barrows",
      "Ritchie, Bradtke and Stiedemann",
      "Jast-McDermott",
      "Stamm-Witting",
      "Satterfield-Lowe",
      "Welch Inc",
      "Pouros-Haag",
      "Goyette Inc",
      "Greenholt, O'Hara and Balistreri",
      "Smith-Stokes",
      "Rodriguez, Yost and Jenkins",
      "Pfeffer LLC",
      "Greenfelder, Bartoletti and Davis",
      "Gutmann, McLaughlin and Wiza",
      "Wuckert-Walter",
      "Conroy Ltd",
      "Donnelly LLC",
      "Hyatt, Russel and Gleichner",
      "Kuhn LLC",
      "Klein Group",
      "Haley, Jewess and Bechtelar",
      "Skiles LLC",
      "Kessler Inc",
      "Hamill-Daugherty",
      "Baumbach Ltd",
      "Fritsch LLC",
      "Bernier, Volkman and Hoeger",
      "Ortiz Group",
      "Ernser-Lynch",
      "Collier LLC",
      "Mosciski, Gislason and Mertz",
      "Watsica LLC",
      "Upton PLC",
      "Heaney-Marquardt",
      "Heathcote LLC",
      "Harber Inc",
      "Maggio-Fahey",
      "Champlin, Rolfson and Connelly",
      "Roob LLC",
      "Bode-Schuster",
      "Terry Ltd",
      "Kuhic, Bins and Pfeffer",
      "Fisher-Schowalter",
      "McGlynn-Jaskolski",
      "Lehner, Mosciski and King",
      "Dare, Casper and Bartoletti",
      "Klocko, Runolfsdottir and Breitenberg",
      "Leannon-Ward",
      "Schumm PLC",
      "Greenholt Ltd",
      "Kerluke PLC",
      "Kihn-Fritsch",
      "Romaguera Ltd",
      "Schuppe, Nolan and Hoeger",
      "Kutch-Hegmann",
      "Weimann-Lockman",
      "Mueller, Gerhold and Mueller",
      "Gerlach Inc",
      "Stroman, Hudson and Erdman",
      "Kuvalis Ltd",
      "Dibbert-Green",
      "Padberg-Welch",
      "Roberts, Ryan and Smith",
      "Labadie, Treutel and Bode",
      "Kihn Inc",
      "Kohler, Lindgren and Koelpin",
      "Shields Inc",
      "Cole, Hills and Jewess",
      "Schulist Ltd",
      "Bednar Group",
      "Harris Group",
      "Dooley-Thompson",
      "Dicki Ltd",
      "Kiehn-Emmerich",
      "Schumm, Bauch and Ondricka",
      "Gutmann Ltd",
      "Lemke-Gutmann",
      "Schmidt-Larkin",
      "Goyette, Howell and Collier",
      "Johnston-Casper",
      "Dare-Marvin",
      "Kihn, Abernathy and Douglas",
      "Osinski Inc",
      "Ankunding-Carroll",
      "Cremin, Hamill and Reichel",
      "Moen, Reinger and Murphy",
      "Conroy-Cruickshank",
      "Stiedemann Ltd",
      "Reichel Inc",
      "Keeling-Crist",
      "Jewess LLC",
      "Schroeder Group",
      "Dickinson Ltd",
      "Hayes, Marquardt and Dibbert",
      "Shields-Wunsch",
      "Yost, Schamberger and Windler",
      "Goodwin-Nitzsche",
      "Rowe, Batz and Goodwin",
      "Medhurst, Cartwright and Ebert",
      "Bernhard-Lesch",
      "Hudson-Grady",
      "Koelpin and Sons",
      "Lynch-Wisozk",
      "Balistreri-Nader",
      "Larson-Moen",
      "Conroy, Balistreri and Gorczany",
      "Christiansen-Gusikowski",
      "Abernathy and Sons",
      "Dickinson-Rempel",
      "Rippin, Kub and Mann",
      "Padberg-Sauer",
      "Schmeler-Howe",
      "Koss, McLaughlin and Mayer",
      "Ernser-Feest",
      "Hamill-D'Amore",
      "Terry, Johns and Bins",
      "Frami Group",
      "Kling-Ernser",
      "O'Reilly, Mohr and Purdy",
      "Powlowski-Weimann",
      "Heller, Gutmann and Zieme",
      "Barrows PLC",
      "Dach-Nader",
      "Yost, Block and Koepp",
      "Johns Inc",
      "Bartoletti and Sons",
      "Spinka-Welch",
      "Bahringer, Bergnaum and Quitzon",
      "Tillman, Dickinson and Labadie",
      "Ullrich Ltd",
      "Cormier LLC",
      "Torp, Muller and Borer",
      "Erdman-Ebert",
      "Roob-Okuneva",
      "Jones, Sawayn and Romaguera",
      "Kertzmann LLC",
      "Hills-Witting",
      "Kunze Inc",
      "Bode-Rempel",
      "Reichert, Rowe and Mraz",
      "Turcotte-Halvorson",
      "Bauch-Raynor",
      "Watsica, Haag and Considine",
      "Kutch, Hermiston and Farrell",
      "DuBuque LLC",
      "Bins-Rice",
      "Goldner, Kovacek and Abbott",
      "Koepp-Witting",
      "Schuppe LLC",
      "Kling, Howe and Schneider",
      "Brown, Homenick and Lesch",
      "Towne LLC",
      "Reilly LLC",
      "Towne, Walker and Borer",
      "Schaefer, Fay and Hilll",
      "Bogisich-Weimann",
      "Schmeler Inc",
      "Breitenberg LLC",
      "Nolan-Williamson",
      "Torphy-Kertzmann",
      "Prosacco, Kreiger and Kovacek",
      "Schiller Ltd",
      "Schroeder, Wolff and Hermiston",
      "Rutherford, Homenick and Bergstrom",
      "Quitzon-Goyette",
      "Koepp-Parker",
      "Kovacek, Dibbert and Ondricka",
      "McCullough, Hudson and Schuster",
      "Douglas, DuBuque and McKenzie",
      "Cronin, Kshlerin and Weber",
      "McGlynn-Heathcote",
      "Erdman-Durgan",
      "Jaskolski-Dibbert",
      "Bogisich Inc",
      "Bahringer, Schoen and Corkery",
      "Mante Group",
      "Thiel PLC",
      "Schmidt and Sons",
      "Torphy-Goyette",
      "Lynch Ltd",
      "Huel-Langworth",
      "Gibson-Deckow",
      "Nienow PLC",
      "Lubowitz-Walter",
      "Fritsch and Sons",
      "Larson, Quitzon and Spencer",
      "Metz-Boehm",
      "Morissette-Schaefer",
      "Hahn, Douglas and Schowalter",
      "Kiehn Inc",
      "Kutch, Steuber and Gerhold",
      "Schaefer Ltd",
      "Shanahan-Lehner",
      "Kutch Group",
      "Konopelski, Schneider and Hartmann",
      "Graham and Sons",
      "Kuhn Group",
      "Larkin, Stracke and Greenfelder",
      "McDermott, Osinski and Morar",
      "Bashirian Group",
      "Bradtke, Torp and Bahringer",
      "Herman, Treutel and Dickens",
      "Cummings Group",
      "Weimann, Kuhic and Beahan",
      "Tillman LLC",
      "O'Connell-Ullrich",
      "Brown Inc",
      "Jakubowski Group",
      "Casper, Hand and Zulauf",
      "Kuphal-Predovic",
      "Lesch Ltd"
    ].sort();
export const categories =[
    "health_fitness",
    "grocery_pos",
    "home",
    "kids_pets",
    "travel",
    "shopping_net",
    "misc_net",
    "gas_transport",
    "shopping_pos",
    "misc_pos",
    "grocery_net",
    "personal_care",
    "entertainment",
    "food_dining"
  ].sort();
  export const professions =[
      "Hydrogeologist",
      "Retail buyer",
      "Chief Executive Officer",
      "Communications engineer",
      "Exercise physiologist",
      "Psychotherapist",
      "Chartered legal executive (England and Wales)",
      "Architect",
      "Theme park manager",
      "Race relations officer",
      "Tax adviser",
      "Jewellery designer",
      "Systems developer",
      "Chief Marketing Officer",
      "Dispensing optician",
      "Pharmacist, community",
      "Engineer, production",
      "Psychotherapist, child",
      "Therapist, drama",
      "Town planner",
      "Scientific laboratory technician",
      "Administrator, local government",
      "Civil Service fast streamer",
      "Copywriter, advertising",
      "Audiological scientist",
      "Television/film/video producer",
      "Programmer, multimedia",
      "Psychologist, clinical",
      "Broadcast presenter",
      "Doctor, general practice",
      "Herbalist",
      "Oncologist",
      "Maintenance engineer",
      "Hydrologist",
      "Editor, film/video",
      "Building control surveyor",
      "Podiatrist",
      "Ambulance person",
      "Restaurant manager, fast food",
      "Database administrator",
      "Multimedia programmer",
      "Medical technical officer",
      "Chemical engineer",
      "Glass blower/designer",
      "Air traffic controller",
      "Immigration officer",
      "Sales professional, IT",
      "Higher education careers adviser",
      "Transport planner",
      "Designer, textile",
      "Retail merchandiser",
      "Bookseller",
      "Futures trader",
      "Early years teacher",
      "Broadcast journalist",
      "Commercial horticulturist",
      "Structural engineer",
      "IT trainer",
      "Biochemist, clinical",
      "Learning mentor",
      "Magazine features editor",
      "Firefighter",
      "Art gallery manager",
      "Ship broker",
      "Forest/woodland manager",
      "Engineer, manufacturing",
      "Manufacturing engineer",
      "Pharmacist, hospital",
      "Cytogeneticist",
      "Research officer, trade union",
      "Special educational needs teacher",
      "Dealer",
      "Archivist",
      "Therapist, music",
      "Records manager",
      "Designer, ceramics/pottery",
      "Industrial buyer",
      "Scientist, marine",
      "English as a foreign language teacher",
      "Sport and exercise psychologist",
      "Scientist, audiological",
      "Physicist, medical",
      "Acupuncturist",
      "Heritage manager",
      "Travel agency manager",
      "Financial adviser",
      "Health and safety adviser",
      "Plant breeder/geneticist",
      "Surveyor, land/geomatics",
      "Ecologist",
      "Environmental education officer",
      "Chartered accountant",
      "Scientist, biomedical",
      "Mining engineer",
      "Petroleum engineer",
      "Phytotherapist",
      "Probation officer",
      "Health service manager",
      "Corporate investment banker",
      "Product manager",
      "Accountant, chartered",
      "Animator",
      "Warden/ranger",
      "Health physicist",
      "Horticultural consultant",
      "Clothing/textile technologist",
      "Administrator, education",
      "Scientist, research (physical sciences)",
      "Programme researcher, broadcasting/film/video",
      "Primary school teacher",
      "Tour manager",
      "Orthoptist",
      "Comptroller",
      "Energy manager",
      "Quantity surveyor",
      "Barista",
      "Teacher, secondary school",
      "Event organiser",
      "Therapist, horticultural",
      "General practice doctor",
      "Chief of Staff",
      "Optometrist",
      "TEFL teacher",
      "Colour technologist",
      "Training and development officer",
      "Materials engineer",
      "Paramedic",
      "Mechanical engineer",
      "Chief Technology Officer",
      "Television production assistant",
      "Journalist, newspaper",
      "Diagnostic radiographer",
      "Merchandiser, retail",
      "Pensions consultant",
      "Land",
      "Pilot, airline",
      "Barrister",
      "Sub",
      "Scientist, research (maths)",
      "Landscape architect",
      "Community development worker",
      "Toxicologist",
      "Pension scheme manager",
      "Insurance claims handler",
      "Video editor",
      "Human resources officer",
      "Building surveyor",
      "Nutritional therapist",
      "Lexicographer",
      "Buyer, retail",
      "Armed forces training and education officer",
      "Market researcher",
      "Soil scientist",
      "Engineer, land",
      "Patent attorney",
      "Police officer",
      "Television camera operator",
      "Designer, interior/spatial",
      "Advice worker",
      "Naval architect",
      "Environmental health practitioner",
      "Drilling engineer",
      "Geneticist, molecular",
      "Public affairs consultant",
      "Chief Operating Officer",
      "Therapist, occupational",
      "Psychiatrist",
      "Management consultant",
      "Call centre manager",
      "Metallurgist",
      "Buyer, industrial",
      "Sales executive",
      "Chiropodist",
      "Careers adviser",
      "Further education lecturer",
      "Web designer",
      "Marketing executive",
      "Administrator, charities/voluntary organisations",
      "Site engineer",
      "Engineer, mining",
      "Radio producer",
      "Commercial/residential surveyor",
      "Advertising account planner",
      "Fine artist",
      "Lawyer",
      "Claims inspector/assessor",
      "Dancer",
      "Oceanographer",
      "Exhibition designer",
      "Outdoor activities/education manager",
      "Medical sales representative",
      "Systems analyst",
      "Archaeologist",
      "Librarian, public",
      "Medical secretary",
      "Trading standards officer",
      "Presenter, broadcasting",
      "Nature conservation officer",
      "Airline pilot",
      "Environmental consultant",
      "Magazine journalist",
      "Wellsite geologist",
      "Radiographer, therapeutic",
      "Editor, magazine features",
      "Producer, radio",
      "Operations geologist"
    ].sort();
